name: hadeet
description: 'A Haddet app.'

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  flutter_bloc: ^8.1.1
  hydrated_bloc: ^9.0.0
  go_router: ^14.2.7
  cupertino_icons: ^1.0.6
  dio: ^5.7.0
  get_storage: ^2.1.1
  flutter_svg: ^2.0.10+1
  bounce: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.0.0
  build_runner: ^2.0.0
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
